<section class="hero-section">
    <div class="hero-slider-container" id="heroSlider">
        <!-- Slides -->
        <!-- Slide 1 -->
        <div class="hero-slide active">
            <img src="https://placehold.co/1920x600/1D3557/FFFFFF?text=Empowering+Communities" alt="Empowering Communities">
        </div>
        <!-- Slide 2 -->
        <div class="hero-slide">
            <img src="https://placehold.co/1920x600/E63946/FFFFFF?text=Education+for+All" alt="Education for All">
        </div>
        <!-- Slide 3 -->
        <div class="hero-slide">
            <img src="https://placehold.co/1920x600/457B9D/FFFFFF?text=Healthcare+Initiatives" alt="Healthcare Initiatives">
        </div>
        
        <!-- Navigation Buttons -->
        <button class="slider-btn prev-btn" id="prevBtn"><i class="fas fa-chevron-left"></i></button>
        <button class="slider-btn next-btn" id="nextBtn"><i class="fas fa-chevron-right"></i></button>

        <!-- Dots -->
        <div class="slider-dots" id="sliderDots">
            <!-- Dots will be generated by JS -->
        </div>
    </div>
</section>

<script>
    document.addEventListener('DOMContentLoaded', function() {
        const slides = document.querySelectorAll('.hero-slide');
        const dotsContainer = document.getElementById('sliderDots');
        const prevBtn = document.getElementById('prevBtn');
        const nextBtn = document.getElementById('nextBtn');
        let currentSlide = 0;
        let slideInterval;
        const intervalTime = 5000; // 5 seconds

        // Create dots
        slides.forEach((_, index) => {
            const dot = document.createElement('div');
            dot.classList.add('dot');
            if (index === 0) dot.classList.add('active');
            dot.addEventListener('click', () => {
                goToSlide(index);
                resetTimer();
            });
            dotsContainer.appendChild(dot);
        });

        const dots = document.querySelectorAll('.dot');

        function updateSlides() {
            slides.forEach(slide => slide.classList.remove('active'));
            dots.forEach(dot => dot.classList.remove('active'));

            slides[currentSlide].classList.add('active');
            dots[currentSlide].classList.add('active');
        }

        function nextSlide() {
            currentSlide = (currentSlide + 1) % slides.length;
            updateSlides();
        }

        function prevSlide() {
            currentSlide = (currentSlide - 1 + slides.length) % slides.length;
            updateSlides();
        }

        function goToSlide(index) {
            currentSlide = index;
            updateSlides();
        }

        function resetTimer() {
            clearInterval(slideInterval);
            slideInterval = setInterval(nextSlide, intervalTime);
        }

        // Event Listeners
        nextBtn.addEventListener('click', () => {
            nextSlide();
            resetTimer();
        });

        prevBtn.addEventListener('click', () => {
            prevSlide();
            resetTimer();
        });

        // Initialize Auto Slide
        resetTimer();
    });
</script>
